spring:
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
		suffix: .html

spring:
	messages:
		basename: i18n.messages
